In [2]:
try:
    import rr
except ModuleNotFoundError:
    import sys
    import os
    path = list(filter(lambda p: p.endswith('site-packages'), sys.path))[0]
    parts = path.split(os.sep)
    new_parts = []
    for part in parts:
        if part == 'lib':
            break
        new_parts.append(part)
        path = os.sep.join(new_parts + ['bin', 'pip3'])
    print(f'Try running this in a new cell: !{path}', 'install -U result-reporter --index-url=https://pypi.org/simple')

rr.set_global_endpoint('https://result-reporter.com/ingest')
rr.set_global_token('ad81bded-291a-4c5e-ac61-eac0035c9057')

**Intro**

This notebook should be treated more as lecture notes than an exercise set. It covers the basics of Numpy and provides some challenges along the way. 

**Challenge**

Complete the challenge questions as they appear.

# Numpy

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

How is a np.array better than list?
1. Space
1. Speed

Arrays have the concept of a type and this allows data to be placed closer together. We only need to use enough bits to hold the value and nothing more; no metadata necessary. Also, since arrays have this notion of a type, it numpy can use specialized low level functions for them that are much faster than Python's high level equivalents.

In [6]:
import timeit

timeit.timeit('sum(random.random() for i in range(500))', setup='import random', number=100000)

7.958268598000004

In [7]:
timeit.timeit('np.random.rand(500).sum()', setup='import numpy as np', number=100000)

0.8947669329999997

Don't use Python loops! Use numpy functions and methods. Ufuncs (or Universal Functions)

In [8]:
# You can create arrays with different types but you loose speed in numpy functions
a = np.array([1, None, False])  
a

array([1, None, False], dtype=object)

In [9]:
a.dtype

dtype('O')

In [10]:
a = np.array([1.0, 2.0, 3.0])  # What if we want to specify the type of the data?
a

array([1., 2., 3.])

In [11]:
a.dtype

dtype('float64')

In [12]:
# What can you do with an array?
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Basic linear algebra!
a + b

array([5, 7, 9])

In [13]:
a - b

array([-3, -3, -3])

In [14]:
a * b

array([ 4, 10, 18])

In [15]:
a ** b

array([  1,  32, 729])

In [16]:
a[:2]  # Slicing just like Python lists

array([1, 2])

In [17]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.linspace(start=1, stop=10, num=77)  # Inclusive of endpoints

array([ 1.        ,  1.11842105,  1.23684211,  1.35526316,  1.47368421,
        1.59210526,  1.71052632,  1.82894737,  1.94736842,  2.06578947,
        2.18421053,  2.30263158,  2.42105263,  2.53947368,  2.65789474,
        2.77631579,  2.89473684,  3.01315789,  3.13157895,  3.25      ,
        3.36842105,  3.48684211,  3.60526316,  3.72368421,  3.84210526,
        3.96052632,  4.07894737,  4.19736842,  4.31578947,  4.43421053,
        4.55263158,  4.67105263,  4.78947368,  4.90789474,  5.02631579,
        5.14473684,  5.26315789,  5.38157895,  5.5       ,  5.61842105,
        5.73684211,  5.85526316,  5.97368421,  6.09210526,  6.21052632,
        6.32894737,  6.44736842,  6.56578947,  6.68421053,  6.80263158,
        6.92105263,  7.03947368,  7.15789474,  7.27631579,  7.39473684,
        7.51315789,  7.63157895,  7.75      ,  7.86842105,  7.98684211,
        8.10526316,  8.22368421,  8.34210526,  8.46052632,  8.57894737,
        8.69736842,  8.81578947,  8.93421053,  9.05263158,  9.17

In [18]:
# How to join two arrays
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [19]:
b = np.arange(5, 10)
b

array([5, 6, 7, 8, 9])

In [20]:
a + b  # Does not join arrays. It adds them.

array([ 5,  7,  9, 11, 13])

In [21]:
np.concatenate((a, b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
def get_floats(x) -> np.array:
    """
    Return an np.array of x equally spaced points between 0 and 1.
    """
    
    return np.linspace(start=0, stop=1, num=x)



In [23]:
### BEGIN TESTS
with rr.Wrap(get_floats) as func:
    result = func(1)
    assert result == np.array([0.]), result
### END TESTS

In [24]:
### BEGIN TESTS
with rr.Wrap(get_floats) as func:
    result = func(7)
    expected = np.array([
        0.0,
        0.16666667,
        0.33333333,
        0.5,
        0.66666667,
        0.83333333, 
        1.0,
    ])
    assert np.round(np.absolute((result - expected).sum()), decimals=int(1e-10)) == 0.0
### END TESTS